Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,16 +15,18 @@
 
 stages:
   - build
-  - test
-  - deploy
-  - cleanup
+  # - test
+  # - deploy
+  # - cleanup
 
 
 default:
   tags:
-    - mac-self-hosted
+    - risha
 
 build:
+  tags:
+    - risha
   stage: build
   script:
     - echo "Building the images..."
@@ -33,37 +35,37 @@ build:
   rules:
     - if: '$CI_COMMIT_BRANCH == "project"'
 
-test:
-  stage: test
-  script:
-    - docker-compose up -d
-    - npm install
-    # Pass CI variables directly to the test command
-    - NGINX_USER=$NGINX_USER NGINX_PASS=$NGINX_PASS node tests/basic-api-tests.js
-  variables:
-    NGINX_USER: $NGINX_USER  
-    NGINX_PASS: $NGINX_PASS
-  rules:
-    - if: '$CI_COMMIT_BRANCH == "project"'
+# test:
+#   stage: test
+#   script:
+#     - docker-compose up -d
+#     - npm install
+#     # Pass CI variables directly to the test command
+#     - NGINX_USER=$NGINX_USER NGINX_PASS=$NGINX_PASS node tests/basic-api-tests.js
+#   variables:
+#     NGINX_USER: $NGINX_USER  
+#     NGINX_PASS: $NGINX_PASS
+#   rules:
+#     - if: '$CI_COMMIT_BRANCH == "project"'
 
-deploy:
-  stage: deploy
-  script:
-    - echo "Deploying application..."
-    - docker-compose up -d
-    - sleep 10
-    - |
-      response=$(curl -s -o /dev/null -w "%{http_code}" -u "${NGINX_USER}:${NGINX_PASS}" http://localhost:8198)
-      if [ "$response" != "200" ]; then
-        echo "Deployment verification failed"
-        exit 1
-      fi
-  rules:
-    - if: '$CI_COMMIT_BRANCH == "project"'
+# deploy:
+#   stage: deploy
+#   script:
+#     - echo "Deploying application..."
+#     - docker-compose up -d
+#     - sleep 10
+#     - |
+#       response=$(curl -s -o /dev/null -w "%{http_code}" -u "${NGINX_USER}:${NGINX_PASS}" http://localhost:8198)
+#       if [ "$response" != "200" ]; then
+#         echo "Deployment verification failed"
+#         exit 1
+#       fi
+#   rules:
+#     - if: '$CI_COMMIT_BRANCH == "project"'
 
-cleanup:
-  stage: cleanup
-  script:
-    - docker-compose down
-    - docker system prune -f
-  when: manual
+# cleanup:
+#   stage: cleanup
+#   script:
+#     - docker-compose down
+#     - docker system prune -f
+#   when: manual
